### ISSUE TITLE
Transaction Buy and Sell fields 

### ISSUE THREAD

**Issue by Jopoleon** [Zauberstuhl/go-coinbase#6]
Hello.
In Coinbase API you can see, that method https://developers.coinbase.com/api/v2#show-a-transaction returns json with filed `"buy"` if the type of transaction is buying something. But if type of transaction is selling or another type from list on API documentation, you can't unmarshal response correctly. 
So we need to add additional fields in APITransactionsData struct and add json tags for them. 
```
type APITransactionsData struct {
	.......
	To               APIResource
	Buy              APIResource `json:"buy,omitempty"`
	Sell             APIResource `json:"sell,omitempty"`
	Instant_exchange bool
	.........
}
```

**Comment by Zauberstuhl** [comment]
@Jopoleon thanks for reporting.

can you confirm that https://github.com/Zauberstuhl/go-coinbase/pull/7/files#diff-4c4ea47e6021629957151fecc23a4823 will cover all types?

Cheers, Lukas
